/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MeetingImport } from './routes/meeting'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MeetingRoute = MeetingImport.update({
  path: '/meeting',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, MeetingRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/meeting"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/meeting": {
      "filePath": "meeting.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
